#!/bin/bash
docker run \
    --rm \
    --name wiki \
    -d \
    -v /etc/localtime:/etc/localtime \
    -v /wiki/db:/wiki/db \
    -v /wiki/images:/wiki/images \
    -v /var/log/wiki:/wiki/logs \
    -v /var/backups/wiki:/wiki/backups \
    -e DB_ROOT_PASSWORD="some_password" \
    -e DB_USER_PASSWORD="some_password" \
    -e SERVER="http://localhost:8002" \
    -e LANGUAGE_CODE="en" \
    -e SECRET_KEY="some_key" \
    -e UPGRADE_KEY="some_key" \
    -p 8002:8002 \
        wiki
