#!/bin/bash

setRootPassword() {
    mysqladmin --user=root password "$DB_ROOT_PASSWORD"
}

setUserPassword() {
    mysql --user=root --password="$DB_ROOT_PASSWORD" -e "GRANT ALL ON $DB_NAME.* TO $DB_USER_NAME@localhost IDENTIFIED BY '$DB_USER_PASSWORD';"
}

createDatabase() {
    mysql --user=root --password="$DB_ROOT_PASSWORD" -e "CREATE DATABASE $DB_NAME;"
}

case $1 in
    setRootPassword)
        setRootPassword
        ;;
    setUserPassword)
        setUserPassword
        ;;
    createDatabase)
        createDatabase
        ;;
    *)
        setRootPassword
        setUserPassword
        createDatabase
        ;;
esac
