#!/bin/bash

setRootPassword() {
    mysqladmin --user=root password "$DB_ROOT_PASSWORD"
}

setUserPassword() {
    mysql --user=root --password="$DB_ROOT_PASSWORD" -e "GRANT ALL ON $DB_NAME.* TO $DB_USER_NAME@localhost IDENTIFIED BY '$DB_USER_PASSWORD';"
}

createDatabase() {
    mysql --user=root --password="$DB_ROOT_PASSWORD" -e "CREATE DATABASE $DB_NAME;"
    mv /var/www/html/wiki/LocalSettings.php /var/www/html/wiki/LocalSettings.php.bac
    php /var/www/html/wiki/maintenance/install.php --dbuser wiki --dbpass $DB_USER_PASSWORD --pass password1% --dbname wiki --dbtype mysql --lang en MediaWiki admin
    grep "\$wgSecretKey" /var/www/html/wiki/LocalSettings.php
}

case $1 in
    setRootPassword)
        setRootPassword
        ;;
    setUserPassword)
        setUserPassword
        ;;
    createDatabase)
        createDatabase
        ;;
    *)
        setRootPassword
        setUserPassword
        createDatabase
        ;;
esac
